name = "wiener-proxy"
main = "index.js"
compatibility_date = "2026-03-26"
account_id = "18fe17e199081ab7d6dda74b083290cd"

[vars]
WIENER_ENV = "api-rc"

# Secrets (postavi sa: wrangler secret put IME_SECRETAI):
# WIENER_3SCALE_CLIENT_ID
# WIENER_3SCALE_CLIENT_SECRET
# WIENER_3SCALE_USERNAME
# WIENER_3SCALE_PASSWORD
# WIENER_WING_CLIENT_ID
# WIENER_WING_CLIENT_SECRET
# WIENER_WING_USERNAME
# WIENER_WING_PASSWORD
# WIENER_AGENT_ID
# WIENER_AGENT_CODE
# WIENER_CASHIER_ROLE_ID
